title: Elham Ali, MPH, PMP
logo: https://raw.githubusercontent.com/Elhamyali/elhamyali.github.io/main/images/photo.jpg
description: >
  <br>
  Hi, I’m Elham 👋🏽, a UX researcher and research data scientist with a decade of experience in design research, statistical data analysis, human-centered design, and project management in public health and civic tech.  
  <br><br>
  🎓 As a doctoral student (DrPH) at Johns Hopkins University, I focus on using data science to advance equitable and sustainable food systems and climate resilience.
  <br><br>
  <a href="https://www.linkedin.com/in/elhamali/">View my LinkedIn Profile</a> 

theme: jekyll-theme-minimal

colors:
  crimson: '#900C3F'
