title: Elham Ali, MPH, PMP
logo: https://raw.githubusercontent.com/Elhamyali/elhamyali.github.io/main/images/photo.jpg
description: >
  <br>
  Hi, I’m Elham 👋🏽 I’m a researcher with a decade of experience in research and evaluation, human-centered design, and project management.    
  <br><br>
  I help local and state governments, public health agencies, startups, and civic tech groups user behavior through evidence-based quantitative and qualitative design research and build equity-focused, actionable data products—from maps and dashboards to case studies—so they can make informed and impactful decisions that improve the lives of their communities. I’m especially interested in products that advance equitable and sustainable food systems and climate resilience.
  <br><br>
  <a href="https://www.linkedin.com/in/elhamali/">View my LinkedIn Profile</a> 

theme: jekyll-theme-minimal

colors:
  crimson: '#900C3F'
