title: Elham Ali, MPH, PMP
#logo: /assets/img/headshot_circle.png
description: Mixed-methods researcher with 10 years of experience in human-centered design, data equity, research and evaluation in loca government and public health
show_downloads: false
theme: jekyll-theme-minimal
