project:
  type: website
  output-dir: "docs"
  resources:
    - /publications
    
website:
  title: "Elham Ali"
  description: "Featured work and publications of Elham Ali, MPH, PMP."
  favicon: images/about/elham-ali.jpg
  site-url: https://www.elhamyali.com
  repo-url: https://github.com/Elhamyali/elhamyali.github.io
  back-to-top-navigation: true
  open-graph: 
    locale: es_ES
    site-name: https://elhamyali.com
  page-footer:
    center:
      - text: "Made with <i class='bi bi-heart-fill'></i>, <a href='https://github.com/Elhamyali/elhamyali.github.io' target='_blank'><i class='bi bi-git'></i></a>, and <a href='https://quarto.org/' target='_blank'><img src='https://quarto.org/favicon.png' width=12> quarto</a>"
    left:
      - text: "© 2024 Elham Ali"
  navbar:
    right:
      - href: index.qmd
        text: Featured Work
      - href: publications/index.qmd
        text: Publications
      - href: blog/index.qmd
        text: Blog
      - href: fun/index.qmd
        text: Fun
      - href: about/index.qmd
        text: About
      - icon: github
        href: https://github.com/Elhamyali
        aria-label: GitHub
        target: "_blank"
      - icon: linkedin
        href: https://www.linkedin.com/in/elhamali
        aria-label: Linkedin
        target: "_blank"
      - icon: globe
        href: https://adplist.org/mentors/elham-ali
        aria-label: ADPList
        target: "_blank"
      - icon: envelope
        href: "mailto:elham.yusufali@gmail.com"
        aria-label: Email
        target: "_blank"
        
    pretty-urls: true
   
format:
  html:
    theme:
      light: [cosmo, theme-light.scss]
      dark: [cosmo, theme-dark.scss]
    css: styles.css
    toc: true
    highlight-style: arrow
    include-in-header:
      - https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css
      - https://cdn.jsdelivr.net/npm/glightbox@3.1.0/dist/css/glightbox.min.css
    include-after-body:
      - https://code.jquery.com/jquery-3.5.1.slim.min.js
      - https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js
      - https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js
      - https://cdn.jsdelivr.net/npm/glightbox@3.1.0/dist/js/glightbox.min.js
      - accessibility.js

editor: visual