project:
  type: website
  output-dir: "."

render:
  input-files: ["index.qmd", "about.qmd", "blog.qmd", "fun.qmd", "publications.qmd"]
  
website:
  title: "Elham Ali"
  description: "Featured work and publications of Elham Ali, MPH, PMP."
  favicon: images/about/elham-ali.jpg
  open-graph: true
  page-footer:
        center:
        - text: "© 2024 Elham Ali<br>Site made with <i class='bi bi-heart-fill'></i>, <a href='https://github.com/elhamyali' target='_blank'><i class='bi bi-git'></i></a>, and <a href='https://quarto.org/' target='_blank'><img src='https://quarto.org/favicon.png' width=12> quarto</a>"
  navbar:
    right:
      - href: index.qmd
        text: Featured Work
      # - href: publications.qmd
      #   text: Publications
      # - href: blog.qmd
      #   text: Blog
      - href: fun.qmd
        text: Fun
      - href: about.qmd
        text: About
      - icon: github
        href: https://github.com/Elhamyali
        aria-label: GitHub
      - icon: linkedin
        href: https://www.linkedin.com/in/elhamali
        aria-label: Linkedin
      - icon: globe
        href: https://adplist.org/mentors/elham-ali
        aria-label: ADPList
      - icon: envelope
        href: "mailto:elham.yusufali@gmail.com"
        aria-label: Email
      
format:
  html:
      theme: cosmo
      css: styles.css
      toc: true
      include-in-header:
        - https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css
        - https://cdn.jsdelivr.net/npm/glightbox@3.1.0/dist/css/glightbox.min.css
      include-after-body:
        - https://code.jquery.com/jquery-3.5.1.slim.min.js
        - https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js
        - https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js
        - https://cdn.jsdelivr.net/npm/glightbox@3.1.0/dist/js/glightbox.min.js
editor: visual